name: RSS Third Parties

on:
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  OnePassword:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://1password.statuspage.io/history.atom"
        prefix: "[1Password]"
        dry-run: "false"
        lastTime: "24h"
        labels: "1Password"         
  Slack:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://status.slack.com/feed/rss"
        prefix: "[Slack]"
        dry-run: "false"
        lastTime: "24h"
        labels: "Slack"            
  GitHub:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://www.githubstatus.com/history.rss"
        prefix: "[GitHub]"
        dry-run: "false"
        lastTime: "24h"
        labels: "GitHub"            
  CloudFlare:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://www.cloudflarestatus.com/history.atom"
        prefix: "[CloudFlare]"
        dry-run: "false"
        lastTime: "24h"
        labels: "CloudFlare, indirect" 
  Calendly:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://www.calendlystatus.com/history.rss"
        prefix: "[Calendly]"
        dry-run: "false"
        lastTime: "24h"
        labels: "Calendly"